Pr new pmw module
RaccoonlabDev/mini_v2_node pull request #24
Opened 2024-04-18 14:41 UTC by AsiiaPine

add pwm module for dronecan application with real pwm publishing via uavcan.equipment.esc.Status.

2024-04-22 09:24 UTC, PonomarevDA requested changes

2024-04-22 09:24 UTC, PonomarevDA commented on Src/dronecan_application/params.yaml
> +  note: TTL of LightCommands [ms].
copy paste mistake

2024-04-22 09:24 UTC, PonomarevDA commented on Src/dronecan_application/params.yaml
> +  note: PWM duration when setpoint is min (RawCommand is 0 or Command is 0.0)
actuator.ArrayCommand is within [-1.0, +1.0], where -1.0 is min

2024-04-22 09:24 UTC, PonomarevDA commented on Src/dronecan_application/modules/PWMModule.cpp
> +        if (min <= max && def >= min && def <= max) {
min_pwm can be less than max_pwm

2024-04-22 09:24 UTC, PonomarevDA commented on Src/dronecan_application/modules/PWMModule.cpp
> +    int8_t res =
It doesn't work here because this function returns the number of channels.

2024-04-24 06:35 UTC, AsiiaPine commented on Src/dronecan_application/modules/PWMModule.cpp
> +    int8_t res =
Fixed with
```c++
void PWMModule::array_command_callback(CanardRxTransfer* transfer) {
    if (module_status != ModuleStatus::MODULE_OK) return;
    ArrayCommand_t command;
    int8_t ch_num = dronecan_equipment_actuator_arraycommand_deserialize(
        transfer, &command);
    if (ch_num == 0) {
        return;
    }
```

2024-04-24 06:40 UTC, AsiiaPine commented on Src/dronecan_application/modules/PWMModule.cpp
> +        if (min <= max && def >= min && def <= max) {
Yes, the condition checks if the parameters are ok. Thus, if min is less than max, the condition will be true and no error will occur.
```c++
        if (min <= max && def >= min && def <= max) {
            params[i].min = min;
            params[i].max = max;
            params[i].def = def;
        } else {
            params_error = true;
        }
```

2024-04-24 07:07 UTC, PonomarevDA commented on Src/dronecan_application/modules/PWMModule.cpp
> +        if (min <= max && def >= min && def <= max) {
I mean that min < max is a valid use case. It is not an error.

Just to make it clear:
- For a ESC typically min pwm duration is 1000 us and max is 2000 us.
- For a servo it is different. We may want to rotate it in a different direction and limit the range of motion based on how we mount it in a control surface.

This is from a real usage: A single node controls 2 servos, but they move in opposite directions.

![image](https://github.com/RaccoonlabDev/mini_v2_node/assets/36133264/2001ab7c-05ed-48ce-b0f0-c3cb14305fd4)

I can't come up with a real application, but I think it is also legal to keep def value out of the range between min and max. For example, you may want to just keep 2 states: def when disarmed and min=max when armed.

2024-04-26 19:40 UTC, PonomarevDA requested changes
I tested it. If all parameters are configured correctly, it works. Please, check a few notes.

2024-04-26 19:40 UTC, PonomarevDA commented on Src/dronecan_application/params.yaml
> +  max: 2000
pwm duration can be only within [1000, 2000] us. Please, set all min to 1000 and all max to 2000.
The default value of `pwm.*_min` should be 1000.
The default value of `pwm.*_max` should be 2000.
The default value of `pwm.*_def` should be 1000.

2024-04-26 19:40 UTC, PonomarevDA commented on Src/dronecan_application/params.yaml
> +  default: 100
Let's set the default frequency to 50. According to my experience, most of the servos support it.

2024-04-26 19:40 UTC, PonomarevDA commented on Src/dronecan_application/modules/PWMModule.cpp
> +            logger.log_debug("check parameters");
We should have a delay before we publish first time. Let's say 5 seconds.
If a node have a hardfault or something and goes into infinite reboot, it will flood the bus.

2024-04-26 19:40 UTC, PonomarevDA commented on Src/dronecan_application/modules/PWMModule.cpp
> +        if (min == max) {
min = max is not an error

2024-04-26 19:40 UTC, PonomarevDA commented on Src/dronecan_application/modules/PWMModule.cpp
> +            params[i].max = min;
why it is inverted here?

2024-04-26 19:40 UTC, PonomarevDA commented on Src/dronecan_application/modules/PWMModule.cpp
> +                return;
Let's subscribe on both messages at the beginning of the program and apply a PWM in callback only if the corresponded mode is configured.
This partial subscription doesn't noticeably improves the performance, but it makes it harder to test and configure the node because you need to save params and reboot the node each time you change the cmd_type parameter.
No doubt, ideally we should subscribe on only topics we want and unsubscribe on what we don't need. But unsubscription is not supported by dronecan_application library at the moment.

2024-04-26 19:40 UTC, PonomarevDA commented on Src/dronecan_application/modules/PWMModule.cpp
> +            params[i].max = min;
The feedback is inverted as well 
![image](https://github.com/RaccoonlabDev/mini_v2_node/assets/36133264/2f808613-f6ce-4a5b-b5d7-75d839a70e24)

2024-04-26 19:40 UTC, PonomarevDA commented on Src/dronecan_application/modules/PWMModule.cpp
> +            max_channel = 15;
actuator_id is up to 255, is not it?

2024-04-26 19:40 UTC, PonomarevDA commented on Src/dronecan_application/modules/PWMModule.cpp
> +        uavcanSubscribe(data_type_signature, data_type_id, callback);
It leads to multiple subscriptions on a single topic, let's move it to init function.

2024-04-27 07:41 UTC, AsiiaPine commented on Src/dronecan_application/modules/PWMModule.cpp
> +        uavcanSubscribe(data_type_signature, data_type_id, callback);
Done
```
void PWMModule::init() {
    logger.init("PWMModule");
    for (int i = 0; i < static_cast<uint8_t>(PwmPin::PWM_AMOUNT); i++) {
        PwmPeriphery::init(params[i].pin);
    }
    uavcanSubscribe(UAVCAN_EQUIPMENT_ESC_RAWCOMMAND_SIGNATURE, UAVCAN_EQUIPMENT_ESC_RAWCOMMAND_ID,
                                                                            raw_command_callback);
    uavcanSubscribe(UAVCAN_EQUIPMENT_ACTUATOR_ARRAY_COMMAND_SIGNATURE,
                                                        UAVCAN_EQUIPMENT_ACTUATOR_ARRAY_COMMAND_ID,
                                                        array_command_callback);
}
```

2024-04-27 07:41 UTC, AsiiaPine commented on Src/dronecan_application/modules/PWMModule.cpp
> +            max_channel = 15;
Sure, thanks
```
switch (pwm_cmd_type) {
        case 0:
            max_channel = NUMBER_OF_RAW_CMD_CHANNELS - 1;
            break;
        case 1:
            max_channel = 255;
            break;
        default:
            params_error = true;
            break;
    }
    ```

2024-04-27 07:48 UTC, AsiiaPine commented on Src/dronecan_application/modules/PWMModule.cpp
> +                return;
Yeah, right, lets make unsubcribe function) But for now, I changed the code in the following manner:

Callback functions at the beggining checks if the command corresponds to the chosen one
```

void PWMModule::raw_command_callback(CanardRxTransfer* transfer) {
    if (module_status != ModuleStatus::MODULE_OK || pwm_cmd_type != 0) return;
    RawCommand_t command;
```
The subscription on both topics are performed at init funciton.
Publish status function works same as in the previous commits (publish_status function switch to the corresponding command type status publish function pointer during apply_params())

2024-04-27 08:01 UTC, AsiiaPine commented on Src/dronecan_application/modules/PWMModule.cpp
> +            params[i].max = min;
Yeah, typo from a rush) Thanks
```
        params[i].min = min;
        params[i].max = max;
```

2024-04-27 08:02 UTC, AsiiaPine commented on Src/dronecan_application/params.yaml
> +  max: 2000
Done
![image](https://github.com/RaccoonlabDev/mini_v2_node/assets/70723894/8efb23df-cc95-498b-b7ee-029b893fa101)

2024-04-27 08:06 UTC, AsiiaPine commented on Src/dronecan_application/modules/PWMModule.cpp
> +            logger.log_debug("check parameters");
Done in spin_once() function changed initial next_pub_ms value to 5000 ms.
```
    status_pub_timeout_ms = 1;
    static uint32_t next_pub_ms = 5000;

    if (module_status == ModuleStatus::MODULE_OK &&
        crnt_time_ms > next_pub_ms) {
        publish_state();
        next_pub_ms = crnt_time_ms + status_pub_timeout_ms;
    }
```

2024-04-27 08:09 UTC, AsiiaPine commented on Src/dronecan_application/modules/PWMModule.cpp
> +        if (min == max) {
Done
```
        auto min = paramsGetIntegerValue(params_names[i].min);
        auto max = paramsGetIntegerValue(params_names[i].max);
        auto def = paramsGetIntegerValue(params_names[i].def);
        params[i].def = def;
        params[i].min = min;
        params[i].max = max;
    }
```
Will the mode be used for hardpoint or smth similar?

2024-05-05 20:07 UTC, PonomarevDA commented on Src/dronecan_application/modules/PWMModule.cpp
> +        if (min == max) {
yes

2024-05-05 20:08 UTC, PonomarevDA approved these changes

2024-05-05 20:08 UTC, merged